-- name: UpsertFollower :one
-- sqlc's sqlite parser miscounts column positions when a `--` comment on
-- these query lines contains multi-byte (e.g. Japanese) characters, so
-- keep these comments ASCII-only. createdAt/updatedAt are bound as
-- RFC3339-nanosecond strings generated by the Go caller.
INSERT INTO "Follower" ("actorId", "inbox", "publicKeyPem", "following", "createdAt", "updatedAt")
VALUES (?, ?, ?, 1, ?, ?)
ON CONFLICT ("actorId") DO UPDATE SET
    "following" = 1,
    "inbox" = excluded."inbox",
    "publicKeyPem" = excluded."publicKeyPem",
    "updatedAt" = excluded."updatedAt"
RETURNING *;

-- name: UnfollowByActorID :one
-- Sets an existing follower's following=false; errors if the row does not exist.
UPDATE "Follower"
SET "following" = 0,
    "inbox" = ?,
    "publicKeyPem" = ?,
    "updatedAt" = ?
WHERE "actorId" = ?
RETURNING *;

-- name: CountActiveFollowers :one
SELECT count(*) FROM "Follower" WHERE "following" = 1;

-- name: GetFollowerByActorID :one
SELECT * FROM "Follower" WHERE "actorId" = ?;

-- name: ListActiveFollowerActorIDs :many
SELECT "actorId" FROM "Follower" WHERE "following" = 1 ORDER BY "id" LIMIT ? OFFSET ?;
