-- name: UpsertRelayConnectionAccepted :one
-- Records an Accept received from a relay for a Follow/Subscribe.
-- createdAt/lastAcceptedAt/updatedAt are bound as RFC3339-nanosecond
-- strings generated by the Go caller (see followers.sql for why these
-- comments must stay ASCII-only).
INSERT INTO "RelayConnection" ("actorId", "inbox", "connected", "lastAcceptedAt", "createdAt", "updatedAt")
VALUES (?, ?, 1, ?, ?, ?)
ON CONFLICT ("actorId") DO UPDATE SET
    "connected" = 1,
    "inbox" = excluded."inbox",
    "lastAcceptedAt" = excluded."lastAcceptedAt",
    "updatedAt" = excluded."updatedAt"
RETURNING *;

-- name: ListRelayConnections :many
SELECT * FROM "RelayConnection" ORDER BY "id";

-- name: GetRelayConnectionByActorID :one
SELECT * FROM "RelayConnection" WHERE "actorId" = ?;
