// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: followers.sql

package db

import (
	"context"
)

const countActiveFollowers = `-- name: CountActiveFollowers :one
SELECT count(*) FROM "Follower" WHERE "following" = 1
`

func (q *Queries) CountActiveFollowers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveFollowers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFollowerByActorID = `-- name: GetFollowerByActorID :one
SELECT id, actorId, inbox, publicKeyPem, "following", createdAt, updatedAt FROM "Follower" WHERE "actorId" = ?
`

func (q *Queries) GetFollowerByActorID(ctx context.Context, actorid string) (Follower, error) {
	row := q.db.QueryRowContext(ctx, getFollowerByActorID, actorid)
	var i Follower
	err := row.Scan(
		&i.ID,
		&i.ActorId,
		&i.Inbox,
		&i.PublicKeyPem,
		&i.Following,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveFollowerActorIDs = `-- name: ListActiveFollowerActorIDs :many
SELECT "actorId" FROM "Follower" WHERE "following" = 1 ORDER BY "id" LIMIT ? OFFSET ?
`

type ListActiveFollowerActorIDsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListActiveFollowerActorIDs(ctx context.Context, arg ListActiveFollowerActorIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listActiveFollowerActorIDs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var actorId string
		if err := rows.Scan(&actorId); err != nil {
			return nil, err
		}
		items = append(items, actorId)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowByActorID = `-- name: UnfollowByActorID :one
UPDATE "Follower"
SET "following" = 0,
    "inbox" = ?,
    "publicKeyPem" = ?,
    "updatedAt" = ?
WHERE "actorId" = ?
RETURNING id, actorId, inbox, publicKeyPem, "following", createdAt, updatedAt
`

type UnfollowByActorIDParams struct {
	Inbox        string `json:"inbox"`
	PublicKeyPem string `json:"publicKeyPem"`
	UpdatedAt    string `json:"updatedAt"`
	ActorId      string `json:"actorId"`
}

// Sets an existing follower's following=false; errors if the row does not exist.
func (q *Queries) UnfollowByActorID(ctx context.Context, arg UnfollowByActorIDParams) (Follower, error) {
	row := q.db.QueryRowContext(ctx, unfollowByActorID,
		arg.Inbox,
		arg.PublicKeyPem,
		arg.UpdatedAt,
		arg.ActorId,
	)
	var i Follower
	err := row.Scan(
		&i.ID,
		&i.ActorId,
		&i.Inbox,
		&i.PublicKeyPem,
		&i.Following,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFollower = `-- name: UpsertFollower :one
INSERT INTO "Follower" ("actorId", "inbox", "publicKeyPem", "following", "createdAt", "updatedAt")
VALUES (?, ?, ?, 1, ?, ?)
ON CONFLICT ("actorId") DO UPDATE SET
    "following" = 1,
    "inbox" = excluded."inbox",
    "publicKeyPem" = excluded."publicKeyPem",
    "updatedAt" = excluded."updatedAt"
RETURNING id, actorId, inbox, publicKeyPem, "following", createdAt, updatedAt
`

type UpsertFollowerParams struct {
	ActorId      string `json:"actorId"`
	Inbox        string `json:"inbox"`
	PublicKeyPem string `json:"publicKeyPem"`
	CreatedAt    string `json:"createdAt"`
	UpdatedAt    string `json:"updatedAt"`
}

// sqlc's sqlite parser miscounts column positions when a `--` comment on
// these query lines contains multi-byte (e.g. Japanese) characters, so
// keep these comments ASCII-only. createdAt/updatedAt are bound as
// RFC3339-nanosecond strings generated by the Go caller.
func (q *Queries) UpsertFollower(ctx context.Context, arg UpsertFollowerParams) (Follower, error) {
	row := q.db.QueryRowContext(ctx, upsertFollower,
		arg.ActorId,
		arg.Inbox,
		arg.PublicKeyPem,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Follower
	err := row.Scan(
		&i.ID,
		&i.ActorId,
		&i.Inbox,
		&i.PublicKeyPem,
		&i.Following,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
