// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: followers.sql

package db

import (
	"context"
)

const countActiveFollowers = `-- name: CountActiveFollowers :one
SELECT count(*) FROM "Follower" WHERE "following" = true
`

func (q *Queries) CountActiveFollowers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveFollowers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFollowerByActorID = `-- name: GetFollowerByActorID :one
SELECT id, "actorId", inbox, "publicKeyPem", following, "createdAt", "updatedAt" FROM "Follower" WHERE "actorId" = $1
`

func (q *Queries) GetFollowerByActorID(ctx context.Context, actorid string) (Follower, error) {
	row := q.db.QueryRow(ctx, getFollowerByActorID, actorid)
	var i Follower
	err := row.Scan(
		&i.ID,
		&i.ActorId,
		&i.Inbox,
		&i.PublicKeyPem,
		&i.Following,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unfollowByActorID = `-- name: UnfollowByActorID :one
UPDATE "Follower"
SET "following" = false,
    "inbox" = $2,
    "publicKeyPem" = $3,
    "updatedAt" = now()
WHERE "actorId" = $1
RETURNING id, "actorId", inbox, "publicKeyPem", following, "createdAt", "updatedAt"
`

type UnfollowByActorIDParams struct {
	ActorId      string `json:"actorId"`
	Inbox        string `json:"inbox"`
	PublicKeyPem string `json:"publicKeyPem"`
}

// Undo(Follow)と同じ挙動: 既存のフォロワーをfollowing=falseにする。レコードが存在しない場合はエラーになる。
func (q *Queries) UnfollowByActorID(ctx context.Context, arg UnfollowByActorIDParams) (Follower, error) {
	row := q.db.QueryRow(ctx, unfollowByActorID, arg.ActorId, arg.Inbox, arg.PublicKeyPem)
	var i Follower
	err := row.Scan(
		&i.ID,
		&i.ActorId,
		&i.Inbox,
		&i.PublicKeyPem,
		&i.Following,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFollower = `-- name: UpsertFollower :one
INSERT INTO "Follower" ("actorId", "inbox", "publicKeyPem", "following", "updatedAt")
VALUES ($1, $2, $3, true, now())
ON CONFLICT ("actorId") DO UPDATE SET
    "following" = true,
    "inbox" = EXCLUDED."inbox",
    "publicKeyPem" = EXCLUDED."publicKeyPem",
    "updatedAt" = now()
RETURNING id, "actorId", inbox, "publicKeyPem", following, "createdAt", "updatedAt"
`

type UpsertFollowerParams struct {
	ActorId      string `json:"actorId"`
	Inbox        string `json:"inbox"`
	PublicKeyPem string `json:"publicKeyPem"`
}

// Followと同じ挙動: 既存レコードがあればfollowing/inbox/publicKeyPemを更新し、なければ作成する。
func (q *Queries) UpsertFollower(ctx context.Context, arg UpsertFollowerParams) (Follower, error) {
	row := q.db.QueryRow(ctx, upsertFollower, arg.ActorId, arg.Inbox, arg.PublicKeyPem)
	var i Follower
	err := row.Scan(
		&i.ID,
		&i.ActorId,
		&i.Inbox,
		&i.PublicKeyPem,
		&i.Following,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
