// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Follower struct {
	ID           int64  `json:"id"`
	ActorId      string `json:"actorId"`
	Inbox        string `json:"inbox"`
	PublicKeyPem string `json:"publicKeyPem"`
	Following    bool   `json:"following"`
	CreatedAt    string `json:"createdAt"`
	UpdatedAt    string `json:"updatedAt"`
}

type RelayConnection struct {
	ID             int64          `json:"id"`
	ActorId        string         `json:"actorId"`
	Inbox          string         `json:"inbox"`
	Connected      bool           `json:"connected"`
	LastAcceptedAt sql.NullString `json:"lastAcceptedAt"`
	CreatedAt      string         `json:"createdAt"`
	UpdatedAt      string         `json:"updatedAt"`
}
