// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Follower struct {
	ID           int32            `json:"id"`
	ActorId      string           `json:"actorId"`
	Inbox        string           `json:"inbox"`
	PublicKeyPem string           `json:"publicKeyPem"`
	Following    bool             `json:"following"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	UpdatedAt    pgtype.Timestamp `json:"updatedAt"`
}

type RelayConnection struct {
	ID             int32            `json:"id"`
	ActorId        string           `json:"actorId"`
	Inbox          string           `json:"inbox"`
	Connected      bool             `json:"connected"`
	LastAcceptedAt pgtype.Timestamp `json:"lastAcceptedAt"`
	CreatedAt      pgtype.Timestamp `json:"createdAt"`
	UpdatedAt      pgtype.Timestamp `json:"updatedAt"`
}
