// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CountActiveFollowers(ctx context.Context) (int64, error)
	GetFollowerByActorID(ctx context.Context, actorid string) (Follower, error)
	GetRelayConnectionByActorID(ctx context.Context, actorid string) (RelayConnection, error)
	ListRelayConnections(ctx context.Context) ([]RelayConnection, error)
	// Sets an existing follower's following=false; errors if the row does not exist.
	UnfollowByActorID(ctx context.Context, arg UnfollowByActorIDParams) (Follower, error)
	// sqlc's sqlite parser miscounts column positions when a `--` comment on
	// these query lines contains multi-byte (e.g. Japanese) characters, so
	// keep these comments ASCII-only. createdAt/updatedAt are bound as
	// RFC3339-nanosecond strings generated by the Go caller.
	UpsertFollower(ctx context.Context, arg UpsertFollowerParams) (Follower, error)
	// Records an Accept received from a relay for a Follow/Subscribe.
	// createdAt/lastAcceptedAt/updatedAt are bound as RFC3339-nanosecond
	// strings generated by the Go caller (see followers.sql for why these
	// comments must stay ASCII-only).
	UpsertRelayConnectionAccepted(ctx context.Context, arg UpsertRelayConnectionAcceptedParams) (RelayConnection, error)
}

var _ Querier = (*Queries)(nil)
