// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: relay_connections.sql

package db

import (
	"context"
	"database/sql"
)

const getRelayConnectionByActorID = `-- name: GetRelayConnectionByActorID :one
SELECT id, actorId, inbox, connected, lastAcceptedAt, createdAt, updatedAt FROM "RelayConnection" WHERE "actorId" = ?
`

func (q *Queries) GetRelayConnectionByActorID(ctx context.Context, actorid string) (RelayConnection, error) {
	row := q.db.QueryRowContext(ctx, getRelayConnectionByActorID, actorid)
	var i RelayConnection
	err := row.Scan(
		&i.ID,
		&i.ActorId,
		&i.Inbox,
		&i.Connected,
		&i.LastAcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRelayConnections = `-- name: ListRelayConnections :many
SELECT id, actorId, inbox, connected, lastAcceptedAt, createdAt, updatedAt FROM "RelayConnection" ORDER BY "id"
`

func (q *Queries) ListRelayConnections(ctx context.Context) ([]RelayConnection, error) {
	rows, err := q.db.QueryContext(ctx, listRelayConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RelayConnection
	for rows.Next() {
		var i RelayConnection
		if err := rows.Scan(
			&i.ID,
			&i.ActorId,
			&i.Inbox,
			&i.Connected,
			&i.LastAcceptedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRelayConnectionAccepted = `-- name: UpsertRelayConnectionAccepted :one
INSERT INTO "RelayConnection" ("actorId", "inbox", "connected", "lastAcceptedAt", "createdAt", "updatedAt")
VALUES (?, ?, 1, ?, ?, ?)
ON CONFLICT ("actorId") DO UPDATE SET
    "connected" = 1,
    "inbox" = excluded."inbox",
    "lastAcceptedAt" = excluded."lastAcceptedAt",
    "updatedAt" = excluded."updatedAt"
RETURNING id, actorId, inbox, connected, lastAcceptedAt, createdAt, updatedAt
`

type UpsertRelayConnectionAcceptedParams struct {
	ActorId        string         `json:"actorId"`
	Inbox          string         `json:"inbox"`
	LastAcceptedAt sql.NullString `json:"lastAcceptedAt"`
	CreatedAt      string         `json:"createdAt"`
	UpdatedAt      string         `json:"updatedAt"`
}

// Records an Accept received from a relay for a Follow/Subscribe.
// createdAt/lastAcceptedAt/updatedAt are bound as RFC3339-nanosecond
// strings generated by the Go caller (see followers.sql for why these
// comments must stay ASCII-only).
func (q *Queries) UpsertRelayConnectionAccepted(ctx context.Context, arg UpsertRelayConnectionAcceptedParams) (RelayConnection, error) {
	row := q.db.QueryRowContext(ctx, upsertRelayConnectionAccepted,
		arg.ActorId,
		arg.Inbox,
		arg.LastAcceptedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i RelayConnection
	err := row.Scan(
		&i.ID,
		&i.ActorId,
		&i.Inbox,
		&i.Connected,
		&i.LastAcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
