// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: relay_connections.sql

package db

import (
	"context"
)

const getRelayConnectionByActorID = `-- name: GetRelayConnectionByActorID :one
SELECT id, "actorId", inbox, connected, "lastAcceptedAt", "createdAt", "updatedAt" FROM "RelayConnection" WHERE "actorId" = $1
`

func (q *Queries) GetRelayConnectionByActorID(ctx context.Context, actorid string) (RelayConnection, error) {
	row := q.db.QueryRow(ctx, getRelayConnectionByActorID, actorid)
	var i RelayConnection
	err := row.Scan(
		&i.ID,
		&i.ActorId,
		&i.Inbox,
		&i.Connected,
		&i.LastAcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRelayConnections = `-- name: ListRelayConnections :many
SELECT id, "actorId", inbox, connected, "lastAcceptedAt", "createdAt", "updatedAt" FROM "RelayConnection" ORDER BY "id"
`

func (q *Queries) ListRelayConnections(ctx context.Context) ([]RelayConnection, error) {
	rows, err := q.db.Query(ctx, listRelayConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RelayConnection
	for rows.Next() {
		var i RelayConnection
		if err := rows.Scan(
			&i.ID,
			&i.ActorId,
			&i.Inbox,
			&i.Connected,
			&i.LastAcceptedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRelayConnectionAccepted = `-- name: UpsertRelayConnectionAccepted :one
INSERT INTO "RelayConnection" ("actorId", "inbox", "connected", "lastAcceptedAt", "updatedAt")
VALUES ($1, $2, true, now(), now())
ON CONFLICT ("actorId") DO UPDATE SET
    "connected" = true,
    "inbox" = EXCLUDED."inbox",
    "lastAcceptedAt" = now(),
    "updatedAt" = now()
RETURNING id, "actorId", inbox, connected, "lastAcceptedAt", "createdAt", "updatedAt"
`

type UpsertRelayConnectionAcceptedParams struct {
	ActorId string `json:"actorId"`
	Inbox   string `json:"inbox"`
}

// Accept(Follow/Subscribe)と同じ挙動: リレーからのAcceptを記録する。
func (q *Queries) UpsertRelayConnectionAccepted(ctx context.Context, arg UpsertRelayConnectionAcceptedParams) (RelayConnection, error) {
	row := q.db.QueryRow(ctx, upsertRelayConnectionAccepted, arg.ActorId, arg.Inbox)
	var i RelayConnection
	err := row.Scan(
		&i.ID,
		&i.ActorId,
		&i.Inbox,
		&i.Connected,
		&i.LastAcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
