name: Fly deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          echo "MICROCMS_API_KEY=${{ vars.MICROCMS_API_KEY }}" >> .env
          echo "MICROCMS_SERVICE_DOMAIN=${{ vars.MICROCMS_SERVICE_DOMAIN }}" >> .env
          echo "MY_BCC_EMAIL_ADDRESS=${{ vars.MY_BCC_EMAIL_ADDRESS }}" >> .env
          echo "MY_EMAIL_ADDRESS=${{ vars.MY_EMAIL_ADDRESS }}" >> .env
          echo "SMTP_PORT=${{ vars.SMTP_PORT }}" >> .env
          echo "SMTP_SERVER=${{ vars.SMTP_SERVER }}" >> .env
          echo "SMTP_TOKEN=${{ vars.SMTP_TOKEN }}" >> .env
          echo "SMTP_USERNAME=${{ vars.SMTP_USERNAME }}" >> .env
      - run: flyctl deploy --remote-only
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
