name: テスト
on:
  push:

jobs:
  test-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v7

      - name: Node.jsを準備
        uses: actions/setup-node@v7
        with:
          node-version: 24.19.0

      - name: pnpmを準備
        uses: pnpm/action-setup@v6
        with:
          version: 10.11.1

      - name: 依存関係をインストール
        run: pnpm install

      - name: テストを実行
        run: pnpm test
