name: テスト
on:
  push:

jobs:
  test-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v7

      - name: Node.jsを準備
        uses: actions/setup-node@v7
        with:
          node-version: 24.19.0

      - name: pnpmを準備
        uses: pnpm/action-setup@v6
        with:
          version: 11.21.0

      - name: 依存関係をインストール
        run: pnpm install

      - name: テストを実行
        run: pnpm test

  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v7

      - name: Goを準備
        uses: actions/setup-go@v6
        with:
          go-version-file: backend/go.mod

      - name: ビルド
        run: go build ./...

      - name: vet
        run: go vet ./...

      - name: テストを実行
        run: go test ./...

  test-infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v7

      - name: Node.jsを準備
        uses: actions/setup-node@v7
        with:
          node-version: 24.19.0

      - name: pnpmを準備
        uses: pnpm/action-setup@v6
        with:
          version: 11.21.0

      - name: 依存関係をインストール
        run: pnpm install

      - name: 型チェック
        run: pnpm run build

      - name: cdk synth
        run: pnpm run synth
